server:
  port: 8081
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YifanZou1210/MasterMicroservice.git
          search-paths: /git-config-repo
          default-label: master